### ISSUE TITLE
Report failed database inserts

### ISSUE THREAD

**Issue by marwinski** [gardener/falco-event-ingestor#21]
**What would you like to be added**:

We need a metric for failed database inserts.

**Why is this needed**:

This metric should generally be 0 - we should not loose any requests. If we start loosing events this is a good reason for an investigation.

There is a multitude of reasons why events can be lost: disk full, load too high, configuration errors, programming errors, ...

**Comment by lsroe** [comment]
added metric in https://github.com/gardener/falco-event-ingestor/pull/50
