### ISSUE TITLE
Provide key rotation for JWT signature validation

### ISSUE THREAD

**Issue by marwinski** [gardener/falco-event-ingestor#29]
**What would you like to be added**:

Allow rotation of public key for JWT signature validation. Avoid failed inserts due to timing issues.

**Why is this needed**:

compliance & security

**Implementation proposal**:

The ingestor should be configurable with 2 keys, a primary key, and a secondary key (optional). The primary key is the current key and the secondary key is the previous key. Upon failure to validate a token with the first key, the ingestor should try to validate with the second key. 

As a value add, the ingestor could stop validating with the secondary key after a configurable amount of time (e.g. after 2 days) until the new key has been deployed to all locations (seeds).

**Comment by lsroe** [comment]
This was completed in https://github.com/gardener/falco-event-ingestor/pull/33
