### ISSUE TITLE
Possible scalability issues under high load

### ISSUE THREAD

**Issue by marwinski** [gardener/falco-event-ingestor#51]
**What happened**:

I expect the falco-event-ingestor to become sloppy and/or unresponsive under medium to high load. 

**What you expected to happen**:

The falco-event-ingestor should run fine even in high load scenarios.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

The problem is with the processing: the http request is consumed in a go routine and in that same routine the event is written to the database (e.g. blocked until the event has been written to the database). An additional burden is a limitation of the connection pool for database transactions. This means that under medium load there will be a lot of blocked go routines which might render the ingestor sloppy or even unresponsive.

It would be better for the http side to check the incoming request for validity and then write it to a queue or channel and then return. This may possibly block if the queue/channel gets too full. On the other side one go routine is probably sufficient to write event batches to the database.

**Environment**:

**Comment by lsroe** [comment]
resolved in the following prs
https://github.com/gardener/falco-event-ingestor/pull/60
https://github.com/gardener/falco-event-ingestor/pull/61
https://github.com/gardener/falco-event-ingestor/pull/62
